---
title: 'Terminology: asymptotically unbiased'
author: Thomas Lumley
date: '2025-06-25'
slug: terminology-asymptotically-unbiased
categories: []
tags: []
---

The phrase *asymptotically unbiased* has at least two uses in statistics. Some people use it to mean that sequence of estimators $\hat\theta_n$ of a parameter $\theta$ satisfies
$$\lim_{n\to\infty}E[\hat \theta_n]=\theta.$$
I don't think this is a very interesting property: it's weaker than consistency plus existence of the first moment, and if you're going to do asymptotics you should at least be able to ask for consistency.

I prefer to say $\theta_n$ is asymptotically unbiased if
$$\sqrt{n}(\hat\theta_n-\theta)\stackrel{d}{\to} N(0,\sigma^2)$$
If you want a more general version, there's some normalising sequence $r_n$ such that
$$\sqrt{r_n}(\hat\theta_n-\theta)\stackrel{d}{\to} X$$
where $X$ is a non-degenerate distribution with mean zero. Or maybe median zero. Something like that.

In other words, I want *asymptotically unbiased* to mean that the *asymptotic distribution* is unbiased, so that (in large samples) the bias is a negligible component of the mean squared error and we can compare estimators by their variances.

Estimators that aren't asymptotically unbiased include density estimators, which optimally have $$n^{2/5}(\hat f(x)-f(x))\stackrel{d}{\to} (\delta(x),\sigma^2(x))$$
for non-zero $\delta$.  BLUPs^[Yes, I do know what the U stands for. Fight me.] of random effects aren't asymptotically unbiased under asymptotics where random effects are interesting. Lasso estimators aren't asymptotically unbiased. 

It's interesting that there any naturally-occurring asymptotically unbiased estimators, and even more so that the efficient estimators in parametric models are asymptotically unbiased.  There doesn't seem to be any intuitive reason that this has to be true.
