---
title: Top posts in 2021
author: Thomas Lumley
date: '2021-12-31'
slug: top-posts-in-2021
categories: []
tags: []
---

1. [From 2020:](https://notstatschat.rbind.io/2020/08/04/weights-in-statistics/), the different ways the term "weights" is used in statistics and when it matters. See also, [when is and isn't it ok to just subset a survey data set by dropping records](https://notstatschat.rbind.io/2021/07/22/subsets-and-subpopulations-in-survey-inference/)
2. [From 2019:](https://notstatschat.rbind.io/2019/02/09/what-have-i-got-against-the-shapiro-wilk-test/) What have I got against the Shapiro-Wilk test?
3. [From May:](https://notstatschat.rbind.io/2021/05/02/generalisability-prediction-and-causation/) Why causal models are relevant to prediction: because they are relevant to *generalisation*. See also, [mushrooms as an example](https://notstatschat.rbind.io/2019/02/01/recognising-when-you-don-t-know/)
4. [From February:](https://notstatschat.rbind.io/2021/02/11/co-linearity/) Co-linearity. *"Collinearity diagnostics aren’t much help, because they don’t tell you whether you’re interested in $\beta_X$ or $\gamma_X$. What they tell you is that if you’re interested in $\gamma_X$ it sucks to be you, because the data don’t provide much information about $\gamma_X$"*
5. [The April 1 post.](https://notstatschat.rbind.io/2021/04/01/a-modest-proposal-for-matrix-multiplication/) You can do matrix multiplication with joins. This is not completely a joke
6. [From August:](https://notstatschat.rbind.io/2021/08/21/pdf-is-not-a-repository/) Pictures of code are not code

And one that didn't get popular but that I liked: [Data is the new oil](https://notstatschat.rbind.io/2021/08/07/the-new-oil/)