baseurl = "http://notstatschat.rbind.io/"
languageCode = "en-us"
title = "Biased and Inefficient"
theme = "hugo-lithium"
googleAnalytics = "UA-120366445-1"
disqusShortname = "notstatschat-netlify-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/tslumley/notstatschat"
[[menu.main]]
    name = "Mastodon"
    url = "https://fediscience.org/@tslumley"

[params]
    description = "A website built through Hugo and blogdown."


    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "notstatschat_1.png"
    width = 75
    height = 100
    alt = "Logo"

