---
title: Single Transferable Vote and blocs
author: Thomas Lumley
date: '2025-07-10'
slug: single-transferable-vote-and-blocs
categories: []
tags: []
---

Suppose you have a single transferable vote election to pick some number $d$ of people, and that you belong to a large voting bloc of sheeplike followers or of cooperative forward-thinkers (delete as necessary). How should you all vote?

I think the following is true:

If there is a set of $k$ or more candidates such that everyone in your block ranks all those candidates above any candidates not in the set, and your block has more than $r/(d+1)$ fraction of the total vote, with $k\geq r$, these candidates will win $r$ positions. (The only point of $k$ here is that you trivially can't win two positions with only one candidate)


**Proof**

First suppose there are no exhausted ballots.  At every step in the voting your set will have more than $r/(d+1)$ fraction of the vote, so no collection of candidates outside your set can have the $d-r$ quotas of more than $1/(d+1)$ fraction needed to win $d-r$ positions.  

By assumption there are no exhausted ballots in your block until after all $k$ of your candidates have been eliminated, so exhaustion of your ballots can't affect whether your candidates win. Exhausted ballots outside your block can't stop your candidate winning. QED



So:

- if you can agree on your candidates you do not need to further agree on any subset of your candidates to rank or on the within-block ranking
- your ranking or non-ranking of the candidates outside your set doesn't affect the result if you have enough votes to win all the positions
- if you prefer your candidates to the other candidates, you can just vote your honest preferences and don't need a block vote. The reasons for block voting are either that you want to cooperate or that you don't know who you actually prefer but do know who is in your party.

There can be more than one such set of candidates. Suppose there are two positions and everyone in your block puts candidates A and B in the first two positions (in some order) and also puts candidates A through H in the first eight positions (in some order). The conditions are satisfied for A through H, so two of A through H will win. The conditions are also satisfied for A and B, so two of A and B will win. 

If your block doesn't have enough votes to sweep the entire election then other candidates will win some positions so it matters how you rank the other candidates. You should just rank them in order of how much you don't want them. It is very hard to do better than that without detailed information on how everyone else votes.