---
title: "My Setup"
author: "Thomas Lumley"
date: 2013-06-08
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 For [UsesThis.com](http://usesthis.com/), prompted by [Luis Apiolaza](http://www.quantumforest.com/2012/04/my-setup/).

**Who are you, and what do you do?**

I'm a statistics professor at the University of Auckland.  I teach, do research in statistics and in epidemiology, and contribute to [R](www.r-project.org).

**What hardware do you use?**

I've been using Mac laptops since 2001. I currently have an aluminium MacBook from 2009 and am waiting on delivery of an 11in MacBook Air. They are nicely solid, have reasonable keyboards, run Unix, and support the Microsoft software that my collaborators use. They are a bit expensive, but worth it. 

Currently, I also use an iMac as a desktop, with the university's Linux-based cluster for serious computing, but I have also recently used Linux on a cheap white-box PC. 

My new phone is from Sony, an older-generation Android phone.  It was the least expensive phone I could find that had a good-enough display to read e-books properly.  My previous phone was an iPhone -- at that time, the cheap competitors weren't really good enough. The phone mostly gets used for reading, Twitter, and maps. 

**And what software?**

For statistics, R and occasionally Stata, and Stan or JAGS for Bayesian modelling.  For scripting, usually R. For coding things that need to be fast, C (gcc) or Java. It's been 10 years since I learned a new language, so I plan to learn JavaScript on my sabbatical, and one of Julia, Haskell, or ocaml. 

Text editor: the Aquamacs version of Emacs, or Apple's TextEdit, or an embedded editor (eg R.app or TeXshop)

Typesetting: TeXLive LaTeX, via TeXshop. 

For collaboration, I use Microsoft Office even though I don't really like wordprocessors -- there are more important things to use my persuasive powers on than choice of software. 

Web browser: varies by device, but preferably Chrome or Firefox.

For presentations:  LaTeX/beamer or PowerPoint or Keynote.  It tends to be PowerPoint when talking to medical researchers (when in Rome...) or trying to be funny, and LaTeX when talking to statisticians. 

For posters: PowerPoint, but I really should learn Illustrator.

Email: various web-based systems. Currently Gmail and (unfortunately, because it's what the university provides) Outlook.  I like the Gmail concept of keeping all your email and searching the full text when you need to find something. 

I use plain paper and gel ink pens, or a whiteboard, for roughing out mathematical ideas, and the whiteboard for explaining things to students.
