---
title: "Welfare as an addictive drug"
author: "Thomas Lumley"
date:  2013-07-15
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 From the [NZ Herald today](http://www.nzherald.co.nz/lifestyle/news/article.cfm?c_id=6&objectid=10898616) 

_Doctors have been told that putting patients on welfare is akin to putting them on "an addictive debilitating drug ... not dissimilar to smoking"._

Smoking is a really, really bad analogy here, since doctors would absolutely never recommend a patient starts smoking.  It's hard to imagine how someone with a medical degree could come up with that analogy. 

Welfare is hard to get off and probably bad for your health, but a better comparison would be something like sleeping pills or opioid analgesics: drugs that are risky, potentially dependence-inducing, and should be taken for the shortest possible time period, but that are absolutely medically necessary at times.

As with opioids, there probably are people on welfare who shouldn't be, and people not able to get on welfare who should be. And, as with opioids, most people don't like being on welfare. 

And if you're going to put this sort of emphasis on the risk of welfare dependence, you need to worry more about the financial penalties for starting work. Today's Herald also has [a story](http://www.nzherald.co.nz/nz/news/article.cfm?c_id=1&objectid=10898604) about someone facing effective marginal tax rates of over 100% for starting work. 
