---
title: "Feynman and the Suck Fairy"
author: "Thomas Lumley"
date: 2014-07-12
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
There's been a bit of...discussion...about Richard Feynman recently. In one Twitter conversation, Richard Easther said he had been thinking of using Feynman's commencement address ["Cargo Cult Science"](http://neurotheory.columbia.edu/~ken/cargo_cult.html) with a first-year physics class, and had decided against.

I was a bit surprised. It's been a long time since I read that piece, but I couldn't remember anything objectionable in it. So I re-read it.  It's still really good in a lot of ways. But. Yeah. That.

The problems are more obvious in Feynman's book of autobiographical anecdotes _"Surely You're Joking, Mr Feynman"_. I read that when it came out, and loved it. I was in high school at the time. It wasn't that I loved the casual sexism; I just didn't really notice. I was interested in the science bits of the book, and I didn't care what he did in bars in Buffalo. It's harder to re-read it now without wincing. 

If you find yourself feeling defensive about Feynman, you might like to read [Jo Walton on the Suck Fairy](http://www.tor.com/blogs/2010/09/the-suck-fairy) in literature. The Suck Fairy goes through books you used to love, and edits them to make them suck when you read them again. The whole point of the name, of course, is that this isn't true; the book always did suck and you just didn't notice when you were younger.  The book you remember is still good, it just isn't real.

The _"Surely You're Joking.."_ I remember, and its author and hero, were great. There's no need to deny that. The problem is, they weren't the actual book and the actual physicist. The actual person was a genius, but not really a role model. 

The imaginary Feynman, the one who wrote the imaginary book I remember reading, would have wanted us to be honest about the faults of the actual Feynman. 
