---
title: "Is it good or bad when confounding adjustment makes no difference?"
author: "Thomas Lumley"
date:  2014-09-24
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 There's a [new paper out](http://jech.bmj.com/content/early/2014/08/08/jech-2014-204274.abstract?sid=255c088d-fa9a-4538-b8d5-2686b5ca0358) in _J Epi Community Health_, looking at the relationship between perceived job insecurity and incident asthma. NHS 'Behind the Headlines' [covers it well](http://www.nhs.uk/news/2014/09September/Pages/Job-insecurity-may-increase-adult-asthma-risk.aspx).

One of the interesting things about the paper is that the crude relative risk between above/below 50% estimated risk of  losing your job is 1.61, and the relative risks after adjustment in three increasingly-complex models are 1.58, 1.62, and 1.61. That is, the adjustment for confounding has no impact at all.

I'm never sure whether this is a good or bad sign. In principle it might mean that there just wasn't any confounding, but it could also mean the control for confounding was completely ineffective.  There are strong risk factors for incident asthma diagnosis (smoking, going to a doctor), but maybe these just aren't related to job insecurity in Germany?
