---
title: "Tomato, tomato"
author: "Thomas Lumley"
date:  2015-01-12
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
There are two* great commandments for conference session chairs

1.  You shall adhere to the schedule with all your heart and all your mind and all your strength
2.  You shall pronounce the speakers' names approximately as they do themselves

For show-biz award ceremonies the first commandment doesn't apply, but the second [still does](http://abcnews.go.com/Entertainment/2015-golden-globes-ricky-gervais-mispronounces-quvenzhane-walliss/story?id=28157683).

In order to pronounce someone's name correctly, you need to ask for the correct pronunciation and have some way of remembering it, such as writing it down phonetically.  

Asking is necessary -- either asking the speaker, or in the case of someone famous, perhaps asking one of her friends or colleagues.  The problem isn't so much with straightforward names such as [Einojuhani Rautavaara](http://en.wikipedia.org/wiki/Einojuhani_Rautavaara), or [Mahela Jayawardene](http://en.wikipedia.org/wiki/Mahela_Jayawardene), or [Kalani Paiʻea Wohi o Kaleikini Kealiʻikui Kamehameha o ʻIolani i Kaiwikapu kauʻi Ka Liholiho Kūnuiākea](http://en.wikipedia.org/wiki/Kamehameha_I). These  you could maybe work out on your own, with a bit of time for research. The problem is names like MacKay (/mɨ'kai/ or /mə'kei/) and Cai (/kai/ or /tsʰai/) that are genuinely ambiguous. 

*and for the Joint Statistical Meetings, the third great commandment: you shall not chair any other session at the meeting, even in an emergency.
