---
title: "It depends on what you mean by 'cost'"
author: "Thomas Lumley"
date: 2014-11-30
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The Tufts Center for the Study of Drug Development has a new cost estimate out: [Cost to Develop and Win Marketing Approval for a New Drug Is $2.6 Billion](http://csdd.tufts.edu/news/complete_story/pr_tufts_csdd_2014_cost_study).

The figure is probably fairly accurate as an estimate of what it's trying to estimate, but it gets quoted in other contexts, so I think it's worth looking at  the number a piece at a time. The Tufts researchers haven't provided enough information to do this, so I'm relying on estimates from [Bruce Booth](http://lifescivc.com/2014/11/a-billion-here-a-billion-there-the-cost-of-making-a-drug-revisited/) (who also has a spreadsheet that you can use for sensitivity analyses).

There are three important issues. First is 'new drug'. This is for a genuinely new drug which needs Phase III testing on real clinical outcomes, with no short-cuts available. 

The second issue is that the cost includes one successful drug and the average number of failures that go with it. The cost for one completely new drug is about \$400 million, but only about 4% of discovery projects produce a new drug. Fortunately, a lot of them fail relatively early and inexpensively, but adding in the cost of the 24 failures takes you from \$400 million to about \$1.4 billion.

The \$1.4 billion cost for a drug is like saying the cost of a lottery ticket is $15 million, because that's what it would cost, on average, to buy enough lottery tickets to get the big prize.  I think it's reasonable to include the cost of failures, but you do then have to remember they are included. You can't say, for example, "It costs \$1.4 billion to develop a new drug, and most of them fail." The fact that most of them fail is already priced in. 

Finally, the \$2.6 billion headline cost includes a cost of capital at 11%/year. This one, I think, is cheating when used in non-technical communication. Opportunity costs or borrowing costs are certainly real, but they are basically never included in the 'cost' figure by normal people.  If you buy a house for \\$500,000 (as you do in Auckland) you say the cost is \$500,000, not the \$1.25 million after mortgage interest or the even larger loss compared to not buying index funds with the money. If you're talking to investment bankers or governments you might want to include the cost of funds, but not when you are giving a number to be used by lay people.
