---
title: "Chemical nerdview"
author: "Thomas Lumley"
date: 2014-02-25 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 [One of Stephen J. Gould's essays](http://www.stephenjaygould.org/library/gould_house-ussher.html) contains the admission

> _I confess that I have always been greatly amused by the term primate, used in its ecclesiastical sense as "an archbishop ... holding the first place among the bishops of a province." My merriment must be shared by all zoologists, for primates, to us, are monkeys and apes--members of the order Primates. _
> 
> _..._
> 
> _But this amusement is silly, parochial, and misguided._

Gould points out that the clerics had the term first, and that the etymology, from the Latin _primas_, first, is just as appropriate (actually, more appropriate) in the ecclesiastical usage as in the zoological one.

Chemists tend to find the concept of 'organic farming' amusing, because they think of the term 'organic' as meaning 'containing carbon atoms', not as indicating derivation from living things.  The chemists are even more at fault than the zoologists, because this sense of organic is not only older than the 'carbon atoms' sense, but actually comes from chemistry, as does the semi-mystical distinction between synthesis in a lab and in a living cell. 

Before 1828, there was a clear division in chemistry between ordinary compounds that could be made in the lab by ordinary chemical procedures and organic chemicals that were produced by living creatures. When Friedrick [Wöhler](http://en.wikipedia.org/wiki/W%C3%B6hler_synthesis) first made the organic compound urea from  inorganic ammonium cyanate he virtually pissed himself in shock, writing to Berzelius

> "_I cannot, so to say, hold my chemical water and must tell you that I can make urea without thereby needing to have kidneys, or anyhow, an animal, be it human or dog_".

Even then, the vitalist idea that organic compounds were special remained for a couple of decades, until [Kolbe](http://en.wikipedia.org/wiki/Adolph_Wilhelm_Hermann_Kolbe) synthesized acetic acid step by step from precursors that were undeniably non-organic (in the old sense).

Chemists then had to adapt their terminology. Since nearly all of the compounds produced only by living cells contained carbon atoms, and vice versa, they could just make a slight shift in definition.  This occasionally caused problems for small molecules without much carbon -- John Clark's book _Ignition_ mentions some confusion over organic vs non-organic nomenclature of rocket fuel compounds -- but worked well enough that many people seem to have forgotten the shift occurred.

The chemists got over vitalism; cells do just work by the same rules of chemistry and physics as test-tubes. Ascorbic acid from a Chinese chemical company really does fail to prevent cancer just as well as natural vitamin C. If complex mixtures of carotenoids turn out to have health benefits not provided by pure beta-carotene, these benefits will just depend on the actual molecules present, not on their origin.

Vitalism in chemistry was wrong, but the vitalist sense of 'organic' is older and was just as rooted in chemistry as the 'carbon atoms' sense. There are better things to sneer at Wholefoods about.
