---
title: "Miasma and Contagion"
author: "Thomas Lumley"
date: 2014-10-25
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Scientists have a nasty habit of taking ordinary English words, turning them into technical terms, and then insisting that the ordinary use is Just Wrong. 'Organic', which I've written about before, is a good example.

On the other hand, sometimes the scientists are right. I complained on Twitter last night about the phrase _'meningococcal virus'_ in a Herald [opinion piece](http://www.nzherald.co.nz/politics/news/article.cfm?c_id=280&objectid=11347878) on state housing, and I have previously complained about the 'Psa virus'  for the bacterium _Pseudomonas syringae_ pv. _actinidiae. _

I checked the Oxford English Dictionary, which reports a general meaning of 'virus', but says it's out of date

> _a. Med. Originally: pus or other discharge produced by an ulcer or wound. Later: a substance produced within the body by a disease, esp. when contagious or infectious or used for vaccination; (also) any agent causing an infectious disease. Now hist. except in the restricted sense 2b._

For the OED to decide a usage is _hist._, it's got to really be _hist._ It's not just sleeping; it's an ex-usage. 

The distinction between viruses and bacteria seems to have become part of English in the 1940s, about the time antibiotics were becoming available. That's probably no coincidence: antibiotics kill bacteria but not viruses, they cure scarlet fever but not measles, so they made the bacteria/virus distinction relevant to everyone. 

Antibiotics are the reason the distinction is even more important today. New Zealand has a problem of both underuse and overuse of antibiotics. Some kids aren't getting penicillin for strep throat, and a few of them end up with rheumatic fever. On the other hand, some people are still getting antibiotics for viral infections or other situations where they are not helpful. 

'Meningococcal virus' is a particularly unfortunate confusion: meningococci are bacteria, and antibiotic treatment is a matter of the greatest possible urgency in suspected meningococcal disease. 