---
title: "Rhetorical sensitivity analysis"
author: "Thomas Lumley"
date: 2014-08-29 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Rhetorical sensitivity analysis  _“The ethanol in alcohol is a group one carcinogen, like asbestos,”_ Prof. Doug Sellman, Otago University ([July 2013](http://www.stuff.co.nz/national/health/8862098/Ethanol-akin-to-asbestos-in-cancer-stakes))

Professor Sellman is correct, of course.  What's more, alcohol is even an important cause of cancer. From the viewpoint of rhetoric and risk communication it's still interesting to see how the effect of the sentence changes when other familiar IARC Group I carcinogens are substituted for 'asbestos'

*   _alcohol is a group one carcinogen, like sunlight_
*   _alcohol is a group one carcinogen, like birth-control pills_
*   _alcohol is a group one carcinogen, like plutonium_
*   _alcohol is a group one carcinogen, like tobacco_
*   _alcohol is a group one carcinogen, like arsenic,_
*   _alcohol is a group one carcinogen, like wood dust_

None of these really has the quite same rhetorical impact; the only one that comes close is  'tobacco'.  

Most of them aren't scary enough: "Oh Noes! Beer is dangerous like sunshine!" 'Plutonium' and 'arsenic' are too scary: the (invalid) risk implication doesn't sound plausible. That's even though 'arsenic' in the IARC sense means low doses in drinking water, not the murder-mystery poison we tend to think of.