---
title: "Randomisation without consent"
author: "Thomas Lumley"
date:  2014-05-14
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 The issue of randomisation without consent has [come up in New Zealand](http://www.nzherald.co.nz/nz/news/article.cfm?c_id=1&objectid=11254381). Because I'm on the HRC Data Monitoring Core Committee, which monitors some NZ clinical trials I don't want to say much about any current NZ clinical trials, even ones we're not monitoring. I do want to talk about the principle.

The always-useful NZ Science Media Centre has rounded up a couple of [bioethicists](http://www.sciencemediacentre.co.nz/2014/05/14/medical-ethics-and-unconscious-patients-experts-respond/) on the topic, and you should read what they say. I'm not a professional bioethicist, but I have been involved in discussions about the ethics and conduct of clinical trials since I was in high school, learning from people with internationally recognised expertise. 

In contrast to physicians, who tend to start off from the doctor-patient relationship, my views have generally been that informed consent, if you could do it right, would be the only thing needed. If research participants understand all the issues and freely choose to take part, it doesn't matter what anyone else thinks.

In practice, though, you can't get perfect informed consent.  Many people don't have the resources to get a really thorough understanding of the issues even when they are healthy, much less when they are sick. They will often go along with a recommendation from their physician, even if she doesn't think she's giving one.

Since you can't get perfect informed consent, you need other safeguards as well. Physicians need to decide whether a trial is suitable to suggest to patients; ethics committees need to decide whether it meets guidelines; paperwork needs to be filled in; whistleblowers need to be protected. 

On the other hand, consent is still primary. New Zealand was home to one of the [dramatic examples](http://www.cartwrightinquiry.com/) of what can happen when clinical research decisions are left to people who think they are on to something. 

Given that I believe participant consent is the primary ethical principle in research and that the other principles are there as safeguards, does that mean I'm opposed to all research without consent? In fact, no. Any research that can be done with informed consent should be done that way.  Any research that can be done with advance consent before people become incompetent should be done that way. Any research where the patient can't consent but a guardian or next-of-kin can consent should be done that way. Any research that can be done with even very limited patient assent (people with some types of mental illness, older children, people with dementia) should be done that way in addition to any other safeguards. And as with any vulnerable group, research should only be done on people who can't give consent if the treatment is _primarily_ intended to benefit precisely that group of people. 

However, I used to live in Seattle. Seattle has a long record of research and development in resuscitation medicine: treatments that are given to people who can't consent because they are basically dead at the time. Not unrelated to that, Seattle has one of the highest survival rates for out-of-hospital cardiac arrest.

There are three possibilities for resuscitation medicine

1.  No new treatments are ever introduced.
2.  New treatments are introduced, but not evaluated
3.  People are randomised without consent

None of these is ideal, but I think the first two are worse than the third. 

It's still important for randomisation without consent to have additional safeguards that aren't needed for normal clinical trials.  In Seattle this included special ethics review, public consultation, public advertisement of how to opt-out of randomisation, and monitoring of how many people withdrew consent once they were in a state to be asked.

That is, the extra safeguards were intended to ensure that trials proceeded without consent only if there wasn't any other way, _and_ if there was good reason to believe people would have consented given the opportunity. If the public consultation was negative or if lots of people withdrew consent for data use, consent to randomisation could no longer be assumed and you pull the plug on the trial. 

In New Zealand there seems to be a term "retrospective consent" for when people wake up and you ask them how they feel about being randomised.  I think this is the wrong way to phrase the issue. We need to recognise that participants are being randomised without consent, just as unconscious patients are routinely treated without consent if there is no alternative. We can, and must, ask patients whether they consent to their data being used, and whether they approve of having been randomised. But that's not consent to randomisation and treatment. It's too late for that. 
