---
title: "What science should everyone know?"
author: "Thomas Lumley"
date: 2014-12-08
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
In response to the question "How much science knowledge should the average person have or should we just encourage people to ask questions?"

> @NaomiShadbolt @petergnz Basics: Atoms; Evolution; "the lights in the sky are suns"; Randomisation; Conservation laws. And ask questions.
> 
> — Thomas Lumley (@tslumley) [December 8, 2014](https://twitter.com/tslumley/status/541879919567831042)

Expanding on this:

*   Atoms: everything is made of a very large but not infinite number of definite, basically indivisible, pieces, and there are very few different types (about 100).
*   Evolution: Complex goal-oriented behaviour in the world mostly came by repeated competition to choose the best-performing of a random set of variations. That's how life developed from single cells: it isn't necessary to have intelligent choice or design. 
*   "the lights in the sky are suns". The stars are the same kind of thing as the sun, but very, very far away, so they appear tiny.
*   Randomisation: The only really reliable way to get a fair comparison between two strategies is random choice of strategy for a large enough set of examples
*   Conservation laws: Many important facts about physics are in the for "the amount of X doesn't change", where X might be energy or mass or momentum or spin or charge. There are deep mathematical reasons for this.

And, above all, the question "Why do you believe this?" is always in order. 