---
title: "How not to treat Ebola"
author: "Thomas Lumley"
date: 2014-12-23
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 From the _[Guardian](http://www.theguardian.com/world/2014/dec/22/ebola-untested-drug-patients-sierra-leone-uk-staff-leave),_ via Mark Henderson of the Wellcome Trust

> _Ebola patients at a treatment centre in Sierra Leone have been given a heart drug that is untested against the virus in animals and humans, a move that has been deemed reckless by one senior scientist and has prompted UK medical staff at the centre to leave._

Ebola is a problem for drug testing. You don't want to leave people untreated, but you do want to find out as fast as possible what works.

I think the following are ethical

*   If you have a candidate treatment with really good support from precliinical studies and that's available in volume, do a randomised-rollout (stepped-wedge) trial. The idea is that you can't get the drug to everyone at the same time, so you might as well choose the first recipients randomly rather than choosing the district where the Minister of Health's family lives.
*   If you have a really good candidate but can't supply it in volume (like the antibody-based treatments used on some Western medical personnel) you might as well randomise who gets the limited supply. This was the rationale for the first modern clinical trial (of streptomycin in tuberculosis) -- that a lottery is better than allocating the limited supply based on wealth or influence (assuming there isn't enough wealth around to have a useful effect on the supply). You could randomise all available patients or limit it to medical or nursing personnel, and I'm glad that isn't my decision.
*   If you have several candidates that are about equally good, randomise which ones go to which patient, so you learn which ones (if any) work.

The drug in Guardian story is [amiodarone](http://en.wikipedia.org/wiki/Amiodarone), which is just being given to people at one clinic. Not only is this not tested in humans or animals, it's not primarily an antiviral and it's a seriously nasty drug. It stays in the body for weeks after you stop taking it; it inhibits the liver enzyme cytochrome P450 3A4, so it has interactions with basically _everything_; and it has numerous unpleasant side-effects.

Amiodarone is still on the market because it's effective for some heart rhythm problems that can't be treated any other way, but you'd want good evidence before you decided it was the preferred treatment in a population of people whose lives depend on flexible and innovative medical care.

Even if amiodarone _did_ turn out to be the miracle anti-Ebola drug, the way it's being used would delay its widespread adoption and cost lives. 
