---
title: "Pi day"
author: "Thomas Lumley"
date:  2015-07-02
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Pi day is celebrated on March 14 in all the countries that use the MM/DD/YYYY date format (ie, the USA). Pi Approximation day is celebrated in the rest of the world on July 22. 

I’m proposing today for another one: π continued fraction day. Like the 22/7 festival it doesn’t depend on using base 10, and like American Pi day it is extensible when the stars align correctly. 

The continued fraction expansion of π is  
$$\pi=3+\frac{1}{7+\frac{1}{15+\frac{1}{292+\frac{1}{1+\cdots}}}}$$  
Taking just a initial segment of this gives the best possible rational expansions: 3, 22/7, 355/113,...

In most years, π continued fraction day will be 3:7, giving the approximation 22/7, slightly better than 3.14. This year, however, it’s 3:7,15, the continued fraction giving $\pi\approx 355/113$, with an error of about $2.7\times 10^{-7}$. That’s two orders of magnitude smaller than the error in 3.1415, and it’s even smaller than the error when the US celebrates Correctly-Rounded Pi Day next year, 3/14/16