---
title: 'JSM2015: notes on Seattle from an ex-resident'
author: "Thomas Lumley"
date: 2015-08-05
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 **Getting from the airport:** Public transport. No question. Well, unless you have significant mobility problems, in which case why are you looking at travel advice from random strangers on the internet? Take the light rail to the end of the line (Westlake), then catch any bus from the same platform one stop to Convention Place. The alternatives are much more expensive, and have a fair chance of being slower.

**Trolls**: The Fremont Troll is under the highway bridge in Fremont. Worth a visit. Take the 26 or 28 bus from whichever downtown ave they’re running on this month. 3rd, maybe?

**Last minute printing**: There’s FedEx in the Convention Center. 

**Psychoactive substances: **

1.  Coffee. Everywhere. If you want something that doesn’t say “Starbucks”, head uphill to Victrola on Pike or Stumptown on Pine. If you don’t mind the mermaid, head uphill to the totally over-the-top Starbucks Reserve, on Pike.
2.  Tea. Starbucks still do not have a clue. There’s a Peets at 904 7th Ave, out the back of the Convention Center and about four blocks logical south.
3.  Beer. Any nearby good places are too small to be worth recommending, except Pike Brewery, at the bottom of Pike St. On the other hand, most places that serve beer have something that even a hipster would reluctantly admit was drinkable. Anything you don’t recognise has a good chance of being ok.  If you head to Fremont (*qv*) try Brouwer’s, 35th & Phinney, for Belgian. 
4.  Chocolate: Fremont (*qv*) has a gourmet chocolate factory, Theo. No, not a confectionery shop; a factory. They make excellent dark chocolate, and also a big range of flavoured things. 
5.  Ok, I’m on record as being in favour of cannabis legalisation, so I should mention the one you’re thinking of. [High Above Seattle](http://www.highaboveseattle.com/seattle-marijuana-stores/) has a list, and it appears there’s at least one in Fremont (*qv*)
6.  Books: All the way up the hill , between Pine and Pike St, one block past Broadway is Elliott Bay Books. The University Bookstore is also excellent (especially for SF/F fans), but not remotely walking distance. The main bookstore in Fremont (*qv*) has closed, but there is a good second-hand store, Opheilia’s, on Fremont Ave just above the main intersection (the cats are not for sale). 

**Former Soviet Dictators**: Fremont (*qv*) also has a statue of Lenin, rescued from Slovakia. It’s historically unusual in showing him as a revolutionary, with guns and flames. 

**Weird architecture**: 

1.  Half-melted, brightly coloured metal (Gehry). The EMP museum at the Seattle Center is a museum focused around rock-and-roll and science fiction. It’s half way to Fremont (*qv*)  
    
2.  Glass and steel origami (Koolhaas). The Central Library actually functions quite well as a library, as well as being an architectural exhibit. The (nonfiction) books are in a long six-storey spiral. The blocky red chairs are more comfortable than they look. Sadly, the view from the top is disappointing. 
3.  Smith Tower: what skyscrapers used to look like, in 1914
4.  The Space Needle. Look, it was 1962, ok? On a completely clear day (which is possible in August) the view is, actually, spectacular.  If you do go, it’s cheaper to book a specific time in advance on the web. 

**Food**:  Most good places are too small to be worth recommending on a blog.  If you have a group of statisticians of a certain age, including some with moderately conservative tastes and/or poor hearing, and want to find somewhere everyone can enjoy, Wild Ginger (downtown) is absolutely reliable, fairly quiet, and not outrageously expensive. 

**Weird sculpture**: In addition to the Troll and Lenin in Fremont (*qv*), there are dinosaurs by the canal (near 34th & Phinney). 

For High Art Weird Sculpture fans there is a sculpture park near the waterfront north of downtown (or west of the Seattle Center). The most dramatic piece is Calder’s _Eagle_, a 40-foot abstract llama in bright orange steel. 