---
title: "Pharmacy ethics"
author: "Thomas Lumley"
date:  2015-03-29
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 ‘You have heard that it was said to those of ancient times, “You shall not murder”; and “whoever murders shall be liable to judgement.”  But I say to you that if you are angry with a brother or sister, you will be liable to judgement.  Matthew 5:21-22  

In practice, we have to distinguish. Whoever murders is liable to judgement, but being angry isn’t enough. In the same way, formal codes of professional ethics come in two versions: the aspirational code that describes the way we want the profession to be, and the legalistic code that describes what will get you kicked out.  In medical research, the [Nuremberg Code](http://www.hhs.gov/ohrp/archive/nurcode.html) is a bare minimum, but the [Declaration of Helsinki](http://www.wma.net/en/30publications/10policies/b3/) goes well beyond current practice (notably on registration and publication of trials and on use of untested treatments). 

The NZ Pharmacy Council code of ethics is supposed to be of the legalistic kind, actually binding on members, but it [says](http://www.pharmacycouncil.org.nz/cms_show_download.php?id=200)

> 6.9 Only purchase, supply or promote any medicine, complementary therapy, herbal remedy or other healthcare product where there is no reason to doubt its quality or safety and when there is credible evidence of efficacy.

Pharmacies very widely fail to follow this principle, and the Society for Science-Based Health has been annoying them by pointing this out, especially in relation to homeopathy. There have been [various defences](http://www.pharmacytoday.co.nz/news/2015/march-2015/16/pharmacists-defend-sale-of-homeopathic-products.aspx): they should be able to sell it because people want it, they should be able to sell it because cultural diversity, they should be able to sell it because quantum*. They may have a point#, but they also have a violation of what are supposed to be legally-enforceable professional standards. If pharmacists honestly believe these arguments, the solution is to change the code of ethics so that it matches reality. Be like the journalists: they will readily admit that horoscopes and reprinted sensationalist linkbait nutribollocks are, all things being equal, undesirable in newspapers. On the other hand, they say, people want it and it pays for the serious investigative journalism. 

Perhaps that’s true of pharmacies as well. Maybe supplying the popular demand for woo is in the public interest, especially if it makes access to qualified pharmacists more widely available for people who want real medications. If so, they should admit it.  At the moment, any pharmacist who sells homeopathy is violating the code of ethics, as is any pharmacist who knows of these breaches and doesn’t report them to the Pharmacy Council.

  

_* I'm not making this up, you know._

_# except about the quantum_