---
title: "Convergent evolution and NZ Bird of the Year"
author: "Thomas Lumley"
date: 2015-10-05
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 Forest & Bird is the New Zealand equivalent of the UK’s Royal Society for the Protection of Birds, or the USA’s Audubon Society. Each year, they hold a “Bird of the Year” competition, to get more publicity for NZ birds.

The [competition](http://www.birdoftheyear.org.nz/) is made possible by the relatively small number of bird species in New Zealand, partly because it’s an isolated set of islands, and partly because a depressing number of the birds are ex-species. The number of NZ species is small enough that there’s room for a few ‘courtesy natives’ that arrived with or after humans. 

Anyone with an email address can vote -- for the beautiful but dumb takahē, the elegant kōkako, the rotund and orotund kereru, the raucous tui, or the Kiwi emblem of the kiwi. 

Since the whole point of the exercise is to come up with superficially plausible rationales for supporting your preferred candidate, I’m going to argue for the [New Zealand wrens](http://www.nzscienceteacher.co.nz/curriculum-literacy/the-living-world/a-new-zealand-evolutionary-story-the-wrens/#.VhItu2SeDGd) -- the rock wren and the rifleman -- as examples of convergent evolution.

Several NZ birds, extant and extinct, can be seen as filling mammalian ecological niches (moa, takahē, kiwi). The wrens, on the other hand, look and behave very much like the northern hemisphere wrens of the family _Troglodytidae,_ and like the Australia fairywrens, emu-wrens, and grasswrens of the family _Maluridae_. 

Despite the clear similarities, the three groups are as unrelated as possible -- their most recent common ancestor would be a common ancestor of most or all modern songbirds. We only know of the lack of relationship from molecular studies: first, analysis of eggwhite proteins, and then [DNA similarity](https://en.wikipedia.org/wiki/Sibley%E2%80%93Ahlquist_taxonomy_of_birds) measured by the binding strength of one species’ DNA to another’s. 

So, in the spirit of the Bird of the Year competition; [VOTE ROCK WREN FOR CONVERGENT EVOLUTION.](https://shar.es/17VtLX)
