---
title: "The Muntab Question"
author: "Thomas Lumley"
date: 2015-12-14
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 In a survey by Public Policy Polling, 30% of Republican-leaning and 20% of Democratic-leaning people said they supported bombing the fictional country of Agrabah. I’ve [written on StatsChat](http://www.statschat.org.nz/2015/12/19/punkd/) why I think these are deliberately misleading percentages and asking the question amounts to  pissing in the swimming pool of public discourse. What I want to say here is that the “Don’t Know”s aren’t getting nearly enough stick.

Now, some of the “Don’t Knows” will have been successfully trolled by PPP and will think Agrabah is actually the name of somewhere in Syria or Iraq where bombing is a genuine question, and a subset of these will legitimately not have given enough attention to the question to be sure. That’s ok. But not-bombing should be the default. If you recognise that you don’t know where Agrabah is, the right answer to “Do you support bombing them?” isn’t “Don’t Know”, it’s  “HELL, NO!”.
