---
title: "New header picture"
author: "Thomas Lumley"
date: 2015-01-12
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
As you can see, there's a new header picture to replace the generic tumblr theme.  It's a pair of Superb Fairywrens, aka blue wrens (*Malurus cyaneus*), one of my favourite Melbourne birds. They're now quite common along the Melbourne coastline from St Kilda down along the bay.

For people in the Northern hemisphere: these are completely unrelated to the wrens you are familiar with, and are also unrelated to the New Zealand wrens. The similarities in appearance and behaviour are due to convergent evolution; the fairywrens and emu-wrens of Australia are most closely related to other Australian birds such as wattlebirds and honeyeaters. The closest common ancestors for the three types of 'wren' are also common ancestors for all songbirds. 

The picture was drawn by NZ artist [Giselle Clarkson](http://www.giselledraws.com/),who mostly does [New Zealand birds](http://thewireless.co.nz/articles/up-with-the-birds-of-rnz) and fish, but was willing to branch out. 