---
title: "One scoRe years"
author: "Thomas Lumley"
date: 2016-07-28
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 It’s always nice when even imperfect metrics make you look good.   

The [new programming-language rankings](http://spectrum.ieee.org/static/interactive-the-top-programming-languages-2016) in IEEE Spectrum are out. I don’t think I believe their weighting system, but it has R in 5th place! Since last year, we’ve just edged out C#.

Bob Muenchen l[ooks at statistical software citations](http://r4stats.com/2016/06/08/r-passes-sas-in-scholarly-use-finally/) on Google Scholar, and finds that R is narrowly in front of SAS -- and though SPSS is well ahead, it’s headed down. I’m not sure how much I believe this metric either, since everything except SAS and SPSS is heading up, even Minitab. The trends in software popularity are probably getting confounded with trends in citation behaviour and changes in what Google can index.

In three weeks time or less I will have been an R user for twenty years: my [first message to the r-alpha mailing list](http://tolstoy.newcastle.edu.au/R/testers/0229.html) was on August 19, 1996, just before version 0.10 came out.

I didn’t expect R to start being used by molecular biologists, ecologists, and linguists. And I think I can speak for everyone at the time in saying we didn’t foresee R being used at Google. 
