---
title: "The hard problem of AI and other stories"
author: "Thomas Lumley"
date: 2016-09-22
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Another occasional SF/F post.

[Amazon now has a lot of older Melissa Scott novels in Kindle format.](https://www.amazon.com/Melissa-Scott/e/B000AQ3XVW)  In the old days, Melissa Scott was known for forthrightly LBGTQ fiction. After a decade or two, there’s been enough social progress for that to not be the most obvious thing about her writing.  

The ‘hard problem of consciousness’ is a term of art in philosophy of mind. It’s either the most important question about intelligence, or a purely linguistic distraction from the real issues. What I call ‘the hard problem of AI’ is something different: when does a program count as people -- and how does that compare to the status of a racial underclass? Melissa Scott’s “Dreaming Metal” is about this problem, as is the earlier *Dreamships*.

*The Kindly Ones* is about honour and honour killings and a traditional society in danger of being wiped out .The first few times I read it, I didn’t realise that the gender of one of the main viewpoint characters is never specified.   

*Burning Bright* is about love, and political intrigue, and role-playing games in a culture where they’re an important spectator sport.   

*Trouble and her Friends* is a queer cyberpunk political mystery. As with cyberpunk in general, the positive aspects are a bit dated. Sadly, many of the negative aspects are still right on target.   

*Point of Hopes* is a young-adult police procedural romance set in a fantasy version of the Dutch Golden Age. It has the best ‘separate but equal’ gender roles I’ve seen: for astrological reasons, local government and shopkeepers tend to be women,and military and long-distance traders tend to be men, but with exceptions in both cases.  There’s a set of sequels -- they’re a bit too similar in plot if you read them all, but any two would be good. 