---
title: "Brief quake summary for overseas people"
author: "Thomas Lumley"
date: 2016-11-14
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There was a [pair of big earthquakes](http://info.geonet.org.nz/display/quake/2016/11/14/M7.5+Kaikoura+Quake%3A+What+we+know+so+far) in New Zealand last night (late Sunday morning UTC, just after midnight Monday NZ time). They were about half-way between Wellington and Canterbury, in the northeast of the South Island. There have been a lot of smaller related quakes [as well](https://twitter.com/kamal_hothi/status/797921821630705664).

Auckland and Dunedin are unharmed. 

Christchurch was shaken but not seriously damaged; some people were evacuated because of the potential for a big tsunami.

There is damage in Wellington, especially in the central business district, exacerbated by even more rain and wind than is usual. Wellington is also worried about aftershocks.

Closer to the quakes, damage is severe. Buildings were destroyed, with two deaths being reported.  The main road and rail line along the coast are broken in multiple places; they aren’t coming back soon.  

Over a much wider area of the country, bridges, rail lines, and water supplies are being checked (a lot of NZ runs on untreated groundwater). 

[Radio NZ](http://www.radionz.co.nz/) is the place to go for more information. 

(And here’s a [snippet of the midnight news broadcast](https://twitter.com/radionz/status/797999347413590017) from Wellington as the quake happened)