---
title: "Information and control"
author: "Thomas Lumley"
date: 2017-07-25
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
There were delays on the Auckland rail system this morning, apparently due to a train hitting a person in south Auckland.  

It seems unreasonable to complain about the delays; Auckland Transport doesn’t have a warehouse of magic inflatable replacement trains, and owing to historic underfunding of trains, there isn’t a lot of redundancy in the physical track network. They actually did a pretty good job of moving around the trains they have, and I was only delayed about twenty minutes.

What they’re absolutely pants at is telling people what is going on.  All the real-time train information on the stations and on Auckland Transport’s app shuts down when something goes wrong -- or, worse, continues but is inaccurate. The announcements mostly tell you to wait for announcements. 

I follow Auckland Transport on Twitter, and they announced that the Southern and Eastern lines would be disrupted, and that you needed to take a bus to get from south Auckland to the isthmus.  They didn’t mention the Onehunga line, which doesn’t go near where the incident happened, and which you might naively expect to be ok.  It was shut down, running just a shuttle to Penrose. Again, in terms of  actual physical movement of trains this makes sense, but not in terms of communication with transit users.

More broadly, trains are big things that move along tracks.  Someone must know where the trains are and where they are heading; it would then be feasible to work out roughly when they are expected to get to other places.  Auckland Transport do a reasonable job of this for buses, and they make the raw information available for other people to try to do better. For trains, not so much.

Seattle, where I used to live, was perhaps the first place to do real-time transit prediction.  An evaluation of the system found that it reduced average waiting time -- but that it reduced *perceived* waiting time by about twice as much as actual waiting time.  Knowing what’s going on helps you maintain a comforting illusion of control over your life, over and above the benefit of helping you make plans.
