---
title: "Haere mai, statistical computing folks"
author: "Thomas Lumley"
date: 2017-09-26
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 Later this year, Auckland is hosting the [Asian regional meeting of the International Association for Statistical Computing](http://www.nzsa2017.com/).  For the benefit of conference-goers, here’s a brief introduction to the locale. 

**Nomenclature**:

The Owen G. Glenn Building (OGGB, or building 260, in university abbreviations) is named after Owen G. Glenn. He’s a New Zealand businessman and philanthropist. 

Auckland is named after George Eden.  The subantarctic Auckland Islands were not named after George but after his father William Eden.

New Zealand is named after the Dutch province of Zeeland; the lack of resemblance is quite striking.

~~Formally~~,(Actually It’s more complicated) the country is Aotearoa New Zealand, with Māori and English names of equal status. The city has a Māori name, Tāmaki Makaurau, but its primary name is the English one.

The Māori language (te reo Māori) is fairly easy to pronounce roughly right. The consonants are the same as in Western European languages (or pinyin), except that ‘wh’ is pronounced /f/. The vowels are pure, as in Spanish or German or Italian. The bars above vowels mean they are about twice as long. There isn’t strong stress on any syllable.

People over 30 who grew up in a place with a Māori name may well use an older, anglicised pronounciation for it, but there’s been a trend away from that. In particular, weather forecasts and airport announcements will typically use something relatively close to the Māori pronounciation.

**Mountains**

Auckland is full of little pointy hills that look like baby volcanoes. They are baby volcanoes. One of them, [Maungawhau/Mt Eden](http://www.maungawhau.co.nz/) is data(volcano) in R. Every few thousand years, a new one pops up at some unpredictable location in the Auckland area, erupts briefly, and then stops. There’s only a few of these volcano fields around the world — another is the (extinct) [Boring Volcano Field](https://volcanoes.usgs.gov/observatories/cvo/cvo_boring.html) in Portland, Oregon. The Auckland one is still active and so is less boring.

The most recent and largest volcano, [Rangitoto](http://www.doc.govt.nz/rangitoto), is just outside the Waitemata Harbour. There are ferry rides a few times a day, and it’s a nice walk to the top. Parts of Rangitoto are still bare rock, parts are pohutukawa forest, and there’s some areas on the south side that have developed proper soil and a variety of plants.

Auckland Domain, just across the motorway from the conference, is the crater of the closest volcano; Mt Eden is a short bus ride away.

**Peoples**

New Zealand was the last worthwhile land mass to be settled — about 800 years ago, by Polynesians in big ocean-going canoes. You occasionally see people raising alt-theories of earlier settlement by, eg, Celts, but there’s scientific consensus and fairly wide social endorsement for the view that these people are probably racist whackjobs.

The British arrived in increasing numbers in the early nineteenth century, with the usual consequences — though the [Treaty of Waitangi](https://www.waitangitribunal.govt.nz/treaty-of-waitangi/) was somewhat more successful than most attempts to negotiate with the British. Recently, the NZ government has settled treaty claims with many iwi (tribes, clans).

At the start of the twentieth century, about one in four residents of New Zealand was an immigrant. The proportion decreased to a minimum of about one in six in the 1940s and has been slowly increasing again. What’s different this time is where the immigrants are from: many are from the Pacific Islands and from Asia.  Auckland, in particular, has about 40%  immigrant proportion,  similar to New York and London. The increase in diversity has gone reasonably well by international standards, but there are certainly some people who aren’t happy with things being different from fifty years ago.  

**Plants**

The trees with dense, gray-green leaves are [pohutukawa](https://www.google.co.nz/search?q=pohutukawa&source=lnms&tbm=isch). Some of them might be flowering by the time of the conference.  Stylised versions of the red spiky puffs of flowers are starting to displace winter-based symbols for Christmas in Auckland. You’ll probably hear people worrying about myrtle rust, a South American fungus that has recently arrived; no-one knows how much damage it will do.

Many of the conifers you see are native: rīmu, tōtara, kauri, kahikatea (native plants are typically known by their Māori names). The things like enormous fake Christmas trees are *Araucaria*s; not native but regional — *A. heterophylla*, ‘Norfolk Pine’ from Norfolk Island and *A. columnaris*, ‘Cook Pine’, from New Caledonia.  There are also two conifers from the Monterey area of California: “radiata” (*Pinus radiata*) and “macrocarpa” (*Cupressus macrocarpa*). They grow much more vigorously here.

The Dr Seuss trees looking like bunches of grass on top of tall trunks are Cabbage Trees (*Cordyline australis*). The name comes from the edibility of the new stem and the roots, rather than their appearance.

Tree ferns are native; the Waitakere hills to the west of Auckland are packed full of them. They’re culturally important: the major women’s professional sports teams are named after them, and the unfolding fern frond (the ‘koru’) is a widely-used symbol of growth.

Kauri are massively huge living-fossil conifers that used to be common in Auckland and points north. Sadly, a lot of the nearby ones were turned into houses, and they grow slowly. Some of the ones on the west side of Northland (day-trip distance) are almost as big as redwoods (*Sequoiadendron*).

New Zealand Flax is known and loved and/or hated by gardeners around the warm temperate world. It was a traditional fibre source, and the nectar was used as a sweetener.  It’s not related to the `true’ flax of the northern hemisphere; it’s a lily.

**Birds**

New Zealand is famous for its weird native birds. The ones you see around you in Auckland mostly aren’t them.  You can easily see a lot of stupidly-introduced English birds: sparrow, starling, pigeon, blackbird, thrush, chaffinch, goldfinch. The cute urban parrots are Australian, as are the magpies and the tiny green silvereyes. The leggy blue and black pūkeko are ‘courtesy natives’ — they arrived before Europeans but after Māori — but they are the same species as the ones all over Europe and Asia. The large black gulls actually are a native species, but the differences would only matter to another gull.

You might, in the parks near the University, see the kererū, the big native pigeon. It’s about twice the size of the feral pigeons, and colored purple, green, and white. There’s a few fantails (pīwakawaka) around, which are very cute.

There’s one common, distinctive, native bird. If you walk past a tree that sounds as if it’s full of old 28k dial-up modems, you have met the tūī. They’re about the size of a blackbird, with a puff of white feathers at the throat, and they’re boisterous, musical, and give the impression of being slightly drunk.

If you want to see more native birds, the day trip to [Tiritiri Maitangi Island](http://www.tiritirimatangi.org.nz/) is highly recommended. You still won’t see kiwi (they are brown, shy, and nocturnal, so are essentially unobservable) but you will likely see saddlebacks and kākāriki and robins and hihi and bellbirds and kēreru and maybe kōkako and takahē.

**Death Rays from Space**

Auckland has a relatively mild climate, since it’s surrounded by water, but we’re the same distance from the equator as Las Vegas or the Greek islands.  There’s also less continental dust in the atmosphere here than a lot of places. It is surprisingly easy to get badly sunburned. 

**Foods**

The best-value inexpensive food in central Auckland is in Asian restaurants, and particularly in Asian food courts. Non-foodcourt examples especially worth mentioning are [Selera](https://www.zomato.com/auckland/selera-newmarket/menu) (Malaysian, in Newmarket) and [Chom Na](https://www.zomato.com/auckland/chomna-lorne-street) (Thai, downtown). Another inexpensive option is fish and chips, which is as good here as anywhere in the world: it’s worth paying extra for snapper if it’s fresh. A lot of pubs also have reasonable food.

The best Indian food is in Sandringham, about 6km south, but there are some good places at the top of the hill, along K Rd ([Satya](http://satya.co.nz/), in particular)

Mexican food is not recommended: it tends to be either bad or expensive. Pizza mostly isn’t great (with a few exceptions). Otherwise, any restaurant that can survive in Auckland is unlikely to be terrible.

At the higher priced end of the market, there are a number of good restaurants on Fort St. [Ima](https://www.imacuisine.co.nz/) does family-style Israeli food very well. [Indochine Kitchen](https://www.indochinekitchen.co.nz/) is Vietnamese, a bit noisy but good flavours.  [Beirut](http://www.beirut.co.nz/) is posh Lebanese. [Cassia](https://www.cassiarestaurant.co.nz/) is modern Indian food and was the Restaurant of the Year last year. There are lots of well-regarded places in Ponsonby that I don’t know much about.  

At the top: for high-end French-style food, [The Grove](https://www.thegroverestaurant.co.nz/) is really excellent; I’ve heard good things about [The French Café](https://www.thefrenchcafe.co.nz/), but have never been there; [Grand Harbour](http://www.grandharbour.co.nz/) does Hong Kong-style seafood and is by acclaim the best Chinese restaurant in the country, but I’m not really qualified to judge whether it’s worth it. The [revolving](https://www.skycityauckland.co.nz/restaurants/orbit/) restaurant on the SkyTower is expensive because it revolves; unlike some revolving restaurants it does actually have good food.

Finally, [Giapo](https://www.giapo.com/), on Fort St, does absolutely over-the-top decorated locavore gelato. You have never seen anything like it.  
