---
title: 'Two-day course: survival analysis'
author: "Thomas Lumley"
date: 2017-07-05
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 **Tuesday 12 and Wednesday 13 September 2017, 9am-5pm. **This two-day workshop will cover data exploration, data summaries, and regression modelling for time-to-event data.  There will be both lecture and practical sessions.

Topics:

*   Concepts: censoring, truncation, competing risks, choice of time scale  
    
*   Summaries: the Kaplan--Meier curve; mean, median, and proportion surviving; the hazard rate; graphical exploration
*   Two-sample testing: the logrank test and its strengths and weaknesses
*   The proportional  hazards model: right censoring, left truncation,   
    
*   Time-varying predictors  
    
*   Modelling recurrent events

Basically, I’m aiming to target the issues that make time-to-event data different from more familiar binary or continuous data. Most of the examples will be medical, but the same issues exist in engineering and in the social sciences.

Participants should be familiar with linear and logistic regression, and should bring a laptop with suitable statistical software. R is preferred, but assistance will probably be available with Stata and SAS.

See the [Statistical Consulting Centre page](https://www.stat.auckland.ac.nz/en/about/statistical-consulting-centre/workshops1.html) for organisational details