---
title: "“Meritocracy” and “public good”"
author: "Thomas Lumley"
date: 2017-03-11
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sometimes a word coined with one intended meaning ends up with a very different one, and after you have fought the good fight and run the race to the finish, you need to just give up. 

My favourite example is “[meritocracy](https://en.wikipedia.org/wiki/The_Rise_of_the_Meritocracy)”, a word coined like “truthiness” and “factoid” to satirically attack a social trend. It failed completely: while “truthiness” worked, and “factoid” still has some of its negative connotation, “meritocracy” now means exactly the concept that it attacked: the supposed ideal of stack-ranking based on a straightforward one-dimensional metric for merit. 

The economist Frances Woolley has [argued persuasively](https://ideas.repec.org/p/car/carecp/06-06.html) that “public good’ is another example, of a slightly different sort. Economists use the term to refer to a precise (and largely non-existent) set of things; the literate public uses it to refer to a vague but almost completely different set. 

In the technical sense a public good is something that is “non-excludable” (so a group of us can’t keep it to ourselves) and “non-rivalrous” (so we wouldn’t even want to, because everyone using it doesn’t reduce the value to us).  In the normal sense, a public good is something it makes sense for the public to supply collectively -- something an economist would describe in terms of “positive externalities”

There’s almost no overlap. I was motivated to write this post by seeing educated and literate people on Twitter recently describe mass transit, education, and libraries as public goods. It’s the first week of the academic year at the University of Auckland, which provides a dramatic example of how all three of these goods are very much both rivalrous and excludable. 

In contrast to “meritocracy” and “organic”, the multiple meanings of “public good” are actually ambiguous and can cause real confusion. It might have been better if the term hadn’t been invented, but the only solution I can see now is for economists to abandon it for some boring acronym, as they abandoned “natural rate of unemployment” for “NAIRU.” 
