---
title: "Hearing things"
author: "Thomas Lumley"
date: 2017-03-05
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 I spend more time than I like on aeroplanes, so I thought I’d write something about my experiences with headphones.

1\. Having something to cut out the engine noise makes a noticeable difference to how much air travel sucks. Maybe as much as 10%.

2\. When I first started to teach R courses for money, in 2001, I bought a pair of Bose noise-cancelling headphones. These make a big difference, and it’s easy to listen to music with them on.

3\. On the other hand, it’s harder to sleep with big padded headphones, and the rigid headband conducts noise if you lean against the seat or the wall. 

4\. Inexpensive Sennheiser noise-isolating earbuds give almost as much protection against engine noise, and probably more against other sounds (such as babies), without a rigid headband. The CX 3.00 is the current version of what I had.  In the US, you can get them for about $45. Recommended

5\. My new earbuds are noise-isolating ones from Shure (model 215), using memory foam to fit in the ears. They’re a bit of a pain to put in, but the noise reduction is noticeably better. On the other hand, they’re more expensive -- even though these are the \$200 ones, not the \$500 ones. Still: highly recommended. 

Your Mileage May Vary: I tend to find planes too hot (especially in the US), so I prefer earbuds over big padded headphones.  Also, the music I listen to is either classical or vocal-led, and so doesn’t depend a lot on bass. The Sennheiser earphones are set quite loud, which can be a problem if you plug them into the airline systems, since the volume control doesn’t control in-flight announcements. 
