---
title: "e-bike-onomics"
author: "Thomas Lumley"
date: 2017-12-30
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 If you own an e-bike, you get used to certain questions: how fast does it go, how often does it need to be charged, how much did it cost?

My e-bike was a bottom-end one two years ago -- I didn’t know if I’d end up using it, so I didn’t spend more than I had to. Since then, the quality has generally gone up, and so has the price. Andrew Chen, [who just bought one](https://www.mcdp.nz/2017/12/a-guide-to-buying-e-bike.html), says that reliable entry-level bikes are \$2500-\$3000. That’s quite a bit of money, but so are other commuting methods.

In the mornings, I take a train to Newmarket then ride to the University. In the evenings I ride all the way home.  That costs me \$1.85 for a train fare. Going by bus all the way both ways costs $6.30, so I save \$4.45 by cycling.  Since I often stop to go shopping on the way home I’d sometimes need to pay an extra fare on the bus -- and before Auckland Transport started proper transfers, shopping would always be an extra fare.

Suppose we use \$4.45/day as the benchmark. At 5 days a week --  reasonable, because while I miss some weekdays, I do ride at weekends too -- that’s \$1157/year. Over three years that’s over  \$3400 -- enough for an e-bike plus maintenance -- and even the battery should last substantially longer than that.

You might think I need to add the cost of electricity: I pay about 30c per kWh; a complete charge is about 1/3 kWh; I probably average less than 3 charges per week. Over three years that’s maybe \$50. 

Now, I’ve got some important advantages here. I can often leave work earlier or later to avoid rain -- and if necessary leave my bike there overnight. Also, I’m at the very end of a train line, so I can be sure of getting my bike on the train in the morning. Still, it’s notable how quickly a bike pays off compared to bus fares -- and the comparison to University parking permit would be even more favourable. Obviously the numbers for a conventional bike would be dramatically better -- but since I’m not going to commute on a conventional bike, that’s not really relevant.  

When electric bikes are expensive but cost-saving at plausible discount rates, there’s interesting potential for employers to subsidise them. 
