---
title: "Order and quotient topologies"
author: "Thomas Lumley"
date: 2017-03-14
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 Over the years when I was intermittently working on the rock-paper-scissors (transitivity) problem in statistical testing, one of the confusing things was the difference between order and quotient topologies. I thought I’d write about why.

Suppose you have two-dimensional Euclidean space, with points $(x,y)$, and you decide to order points on the first coordinate, so $(x,y)\prec(z,w)$ iff $x<z$. This gives you equivalence classes $(x,y)\sim(z,w)$ iff $x=z$.  There are two obvious topologies on the set of equivalence classes. 

The first is the quotient topology, where you just collapse each equivalence class to a point. The function doing the collapsing is $\phi(x,y)=x$ and we define a set $V$ of equivalence classes as open if there is an open set $U$ in the two-d space with $V=\phi(U)$. Thinking heuristically in terms of metrics, $x$ and $z$ are close in the quotient space if there are points $(x,y)$ and $(z,w)$ that are close in the original two-d space.  The quotient topology depends on the original topological structure, but not on the ordering. 

The second topology is the order topology, where the open sets of equivalence classes are generated by the open intervals in the ordering: $(a,b)=\{x: a\prec x\prec b\}$.  This uses the ordering but not the original topological structure.

In the two-dimensional to one-dimensional example these are the same: they both give the standard topology on $\mathbb{R}$.  This happens in a lot of examples, so it’s easy to confuse the two. In particular, it happens when the equivalence classes are a stack of nice tidy surfaces that cut across a finite-dimensional space. Since that was my mental picture of what’s going on, I didn’t realise there could even be a problem. [Update: Debreu’s Theorem, in economics, is a more sophisticated version of this picture]

 An example where the topologies are very different is when you start with cumulative distribution functions under the supremum metric and you order by the mean.  If $F$ is a cdf with mean $\mu$ there are cdfs with any other mean $\\nu$ arbitrarily close to $F$ in the original metric.  The quotient topology isn’t any use for studying the $t$-test.  The order toplogy, though, is still the ordinary topology on $\mathbb{R}$. 