---
title: Journalism and cyber-bullying
author: Thomas Lumley
date: '2018-09-11'
slug: journalism-and-cyber-bullying
---

Newsroom, an online-only New Zealand news site, has written a series of stories critical of Sir Ray Avery and his R&D efforts in medical devices. According to the [most recent story](https://www.newsroom.co.nz/2018/09/10/230522/avery-targets-newsroom-citing-digital-harm), Sir Ray is attempting to use the [Harmful Digital Communications Act](http://www.legislation.govt.nz/act/public/2015/0063/latest/whole.html) to get these stories removed

> *Avery has told Netsafe, the legal agent for considering complaints under the Act, the reports have caused him serious emotional distress and amount to a form of digital harm - and wants Newsroom to consider removing them and to agree not to write further news stories about him.*
>
>*"Ray believes these are written with the purpose of harassing him and contain false allegations," Netsafe has told Newsroom.*

The allegations (linked at the bottom [here](https://www.newsroom.co.nz/2018/09/10/230522/avery-targets-newsroom-citing-digital-harm)) are serious, including [claims](https://www.newsroom.co.nz/2018/09/06/225337/legal-threat-to-suppress-clinical-study) that Sir Ray tried to suppress negative trial results about one of the devices.  It matters to me whether these claims are true: I teach a course on clinical trials for statisticians, which includes a section on ethics, and the question of what you (realistically) should do when someone wants your results to disappear is one of the topics we cover.

In this particular case I don't have any information beyond what's in the Newsroom stories. I'd say it's pretty obvious that these stories have damaged Sir Ray's reputation. If they are untrue or misleading, he should be able to appeal to the [Press Council](http://www.mediacouncil.org.nz/) for a retraction/apology, and he should be able sue for defamation and win fairly large sums of money.  If Newsroom are making this sort of thing up, they need to be laid waste with fire and the sword.  

What this **isn't** is cyberbullying. The Harmful Digital Communications Act is motivated by the fact that some things are much easier to do online than they were before the internet. Doxxing, revenge porn, bot attacks, harassment -- it used to be hard to do this anonymously or on a large scale, and now it's not so hard. That motivation doesn't apply to journalism. 

Irresponsible or malicious journalism is occasionally a problem, and it has been sometimes a problem since well before the internet. Some tools for fighting back against egregious journalism are necessary, but they aren't specifically a digital problem.  If Newsroom are wrong, they are wrong in a way that has nothing to do with the paper vs digital divide.  If the law makes it easier to suppress these stories from an online-only news organisation than from a radio, print, or TV organisation, the law is wrong and needs to be changed.