---
title: "The Ihaka Lectures"
author: "Thomas Lumley"
date: 2018-01-22
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

They’re back!

This year our theme is visualisation. The lectures will again run on Wednesday evenings in March. The three speakers work in different areas of data visualisation: collect the complete set!

[Paul Murrell](https://github.com/pmur002) is an Associate Professor in Statistics here in Auckland. He’s a member of the R Core Development Team, and responsible for a lot of graphics infrastructure in R. The ‘grid’ graphics system grew out of his PhD thesis with Ross Ihaka. 

[Di Cook](http://www.dicook.org/) is Professor of Business Analytics at Monash University, and was previously a Professor at Iowa State University. She’s an expert in visualisation for data analysis: using graphics, especially interactive and dynamic graphics, to learn from data. 

[Alberto Cairo](http://www.thefunctionalart.com/) is the Knight Chair in Visual Journalism at the University of Miami. His focus is in data visualisation for communication, especially with non-specialists.  He led the creation of the Interactive Infographics Department at El Mundo (**[elmundo.es](http://elmundo.es/)**, Spain), in 2000.

More details to follow.