---
title: Spell my name with a ‘v'
author: Thomas Lumley
date: '2018-06-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Admittedly, it's *conceivable* for parents to make a simple error in assigning a child's name.

In a fictional example from Kerry Greenwood's ['Phryne Fisher'](http://phrynefisher.com/) series, the protagonist's hungover father  accidentally named her after [Phryne](https://en.wikipedia.org/wiki/Phryne) the Greek courtesan rather than [Psyche](https://en.wikipedia.org/wiki/Cupid_and_Psyche). In the real world, [Isaac Asimov's father](https://en.wikipedia.org/wiki/Isaac_Asimov#Family_name_etymology) incorrectly transliterated the Cyrllic Азимов as 'Asimov' rather than 'Azimov'.

By and large, though, the idea that someone is simply incorrect about their name or their child's name falls under "not even wrong".

It's *conceivable* that there are parents who had heard of the popular Irish girl's name pronounced [ˈniːəv] and, not realising the weirdness of Irish orthography, thought it was spelt "Neve" rather than "Niamh".  

The idea that the Prime Minister of New Zealand and her partner are in this category beggars belief. 


