---
title: "Graduation"
author: "Thomas Lumley"
date: 2018-05-14
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*So, I gave one of the graduation addresses during Silly Hat Week last week.  It’s not my usual style of writing, but since there’s no point being embarrassed about a speech you’ve already given in front of your boss, your boss’s boss, and 2000 other people, I thought I’d post it here.* 

* * *

Chancellor, Vice-Chancellor, Members of Council, fellow Members of the University, Graduands, families and friends: kia ora tātou

It’s five o’clock on a Friday. In the cultural traditions of my people, that’s a time to celebrate the successful end of some hard work. Today we're celebrating a longer period of harder work than most Fridays, and with two thousand more people than usual.

For some of you, the journey will have been especially challenging: your friends didn't go to university with you, or you've had to juggle family and work and study obligations, or you're studying in a foreign country and a foreign language. But it won't have been easy for anyone: your degree is a real achievement to be proud of.

Congratulations, graduands. You did it.

In a few minutes from now, the Chancellor will say the magic words and it will be official: you know Science. I'm sure I speak for my colleagues on the stage when I say we're all proud to have helped.

Of course, no-one one knows everything about science, but you do know more than most people in New Zealand -- or in the world.  Part of that is the specific facts about plankton or neutrinos or Sonogashira couplings that you've studied. Just as important is what you've learned about how science works: how it fits together like a crossword puzzle, and how you can use what we already know about the world to test answers to new questions.

Some of you will go on to make your own contributions to scientific knowledge -- in fact, some of you already have. Many of you will use what you've learned about science in your future careers.  But I want to talk about a way all of you can use your scientific training to contribute to the community.

Today, scientific research is helping us uncover problems and risks for society and potential solutions to them: climate change, drug policy, road pricing, crime prediction, and many more.  The news media report some of this research, but tend to lose the context it was done in: they don't distinguish well between solid and speculative ideas or between major and minor risks or between breakthroughs and the usual incremental scientific advances. It's not that the journalists don't care, it's that they don't have the time and resources to cover each story in the depth it would need — it’s not sports journalism.

But the news -- and maybe social media -- is how most people get their information about policy issues and the science informing them. And that's a problem.

In a democracy we want decisions made in a way that reflects the whole range of interests and values across society. It's hard to do that unless there's a shared understanding of what the problems and potential solutions are. Either people need to understand the issues themselves or they need to trust someone else's understanding.  

Helping create this shared understanding is partly a job for those of us on the stage -- one of the University's official roles,  according to the legislation that set it up, is to act as a critic and conscience for society. Since I moved to New Zealand I've been spending a lot more time on science communication: blogging, tweeting, talking to journalists and journalism students. Many of my colleagues do the same. But there are things you can do that we can't.  

As I said at the beginning, you know more about science -- both the basic facts, and the ways of answering questions -- than most people in New Zealand, or most people in the world. Knowledge is power, and with modest power comes modest responsibility.   Each of you has the skills and training to understand at least some of the scientific issues in our political and social debates. If you have a smartphone, you've got instant access to a lot of the world's scientific knowledge in a way that was unimaginable fifty years ago. And, most importantly, you've got people -- friends and family -- who trust you to share their values and interests, when they wouldn't trust me.  

I'm not suggesting you go around preaching science to all your friends: that would just get annoying, and you'd end up with fewer friends. But if you keep up the habits of learning from your time at the University, and if you look into issues carefully before making up your mind it's going to have an influence on the people around you -- and sometimes they’ll ask your opinion.

Now, trying to follow the facts behind social issues can be uncomfortable.  Like all of us, you're going to sometimes find out that the arguments you'd like to support are wrong, or at least a lot weaker than you'd like. In fact, finding that you were wrong about something is one of the best signs that you're still doing science right.  

So, I'm going to propose a challenge: at the end of every year when you think about New Year's resolutions, also ask yourself: "What did I change my mind about this year?"

* * *