---
title: The Ihaka Lectures, Episode 4
author: Thomas Lumley
date: '2020-02-19'
slug: the-ihaka-lectures-episode-4
categories: []
tags: []
---

The Ihaka Lectures in computationally-oriented statistics are back!  This year the theme area is social science and policy.  We've got three great speakers:

**Simon Jackman** is a political scientist. He's currently CEO of the United States Studies Centre at Sydney University. He was previously a Professor of Political Science and Statistics at Stanford.  He's interested in the increasingly-difficult area of empirical public opinion research, and will talk about recent successes and failures of predictive models of election outcomes. 

**Jennifer Hill** is Professor of Applied Statistics, co-director of  the Center for Practice and Research at the Intersection of Information, Society, and Methodology (PRIISM) the Master's of Science Program in Applied Statistics for Social Science Research (A3SR) at New York University.  She works on causal inference from relatively complex and messy observational data. Professor Hill will talk about the extent to which modern machine learning helps with these causal inference problems.

**Rhema Vaithianathan** is Professor of Health Economics and director of the Centre for Social Data Analytics at AUT. She She is interested in implementing data-analytics solutions that address entrenched social problems, like child maltreatment and homelessness.  She will talk about emerging ‘rules of engagement’ for social good uses of data analytics, drawing on her experience implementing the Allegheny Family Screening Tool, a machine learning tool used to support screening of child abuse calls in Allegheny County, Pennsylvania

The Ihaka Lectures are on March 9 (Monday), 18 (Wednesday) and 25 (Wednesday), in Lecture Theatre PLT1, Building 303. To find PLT1, enter the Science Building (on Princes St at Wellesley St) through the basement entrace on Princes St.  There will be refreshments served at 6pm and the lectures will begin at 6:30pm. 
