---
title: Phobos and Deimos and public speaking
author: Thomas Lumley
date: '2021-03-19'
slug: phobos-and-deimos-and-public-speaking
categories: []
tags: []
---

The moons of Mars are called *Phobos* and *Deimos*, named for twin sons of the war god *Ares* in Ancient Greek myth. In the past, you'd look for explanations of the names in astronomy books, and they would often give the translations 'terror' and 'fear', respectively, which is a bit unhelpful.  It wasn't until reading Brett Devereaux's [blog post on pre-battle speeches in history vs in the *Lord of the Rings*](https://acoup.blog/2020/06/12/collections-the-battle-of-helms-deep-part-vii-hanging-by-a-thread/) that I learned more about the distinction (though it is now well-described in Wikipedia).

>The Greeks saw the fear of battle as two distinct elements, *deimos* (δεῖμος) -- the creeping dread before battle and *phobos* (φόβος) -- the sudden paralyzing panic in combat, the sharp fear that causes men to flee.

He goes on to explain how this dichotomy influences the structure of real pre-battle speeches from antiquity to this, from Eisenhower's D-Day message

>Your task will not be an easy one. Your enemy is well trained, well equipped and battle-hardened. He will fight savagely.
>
>But this is the year 1944! Much has happened since the Nazi triumphs of 1940-1. The United Nations have inflicted upon the Germans great defeats, in open battle, man to man. Our air offensive has seriously reduced their strength in the air and their capacity to wage war on the ground. Our Home Fronts have given us an overwhelming superiority in weapons and munitions of war, and placed at our disposal great reserves of trained fighting men.

Rather than telling soldiers that everything will be ok, there is a description of the dangers and the strength of the enemy, followed by the reasons to be confident of success despite the challenge.  Minimising the problem helps with deimos, dread before the event, but not with phobos, terror when facing the reality. 

On a smaller scale, the deimos/phobos dichotomy seems relevant to training students^[people in general, but students in my case] to give talks in public. Some are worried in advance, but not when actually speaking; some are happy in advance but tend to fall apart at the time^[me, in earlier days]; some have both problems or neither. The example from the military suggests that simple encouragement, telling people not to worry, will be unhelpful, and that a better message is "yes, you will be scared giving this talk at Big Conference, but it will still be a good talk because we've practiced and you know this research better than anyone, and do you want to run through it again on Thursday?"

