---
title: 'Design |> Data: Ihaka Lectures 2022'
author: Thomas Lumley
date: '2022-06-21'
slug: design-data-ihaka-lectures-2022
categories: []
tags: []
---

They're back. Partly.

We managed to have the Ihaka Lectures in person for 2020 and 2021, but we chickened out on 2022 and are going for internet-based talks. Covid permitting, we will still have an in-person event in Auckland to watch the talks and interact with the speakers. On the bright side, this means we can get great speakers who might not come all the way to Auckland. 

We have

- Emi Tanaka, from Monash University, notable as the creator of the `eddible` package for experimental design. Emi will talk about the 'grammar of experimental design' in her software and how this improves on the 'cookbook' approach you often see. *Thursday 28 July*
- Luke Tierney, of R Core. Luke will talk about the how and why of the pipe operator in base R. *Thursday 4 August*
- Wes McKinney, of Voltron Data. Wes will talk about major trends and areas of work in the broader “data science tools” software ecosystem across Python, R, Julia, and other programming languages *Thursday 11 August*

The talks all start at 6:30pm NZST (Pacific/Auckland, UTC+12).  If you're watching from Auckland, the event will be in  Science Building 303, on Princes St at Wellesley St, on the first floor (enter from Princes St opposite Albert Park.) Refreshments start from 6pm.  More details [here](https://www.auckland.ac.nz/en/science/about-the-faculty/department-of-statistics/ihaka-lecture-series.html)